// Code generated by wit-bindgen-go. DO NOT EDIT.

package add

// Exports represents the caller-defined exports from "dir:sdk/add@0.1.0".
var Exports struct {
	// Add represents the caller-defined, exported function "add".
	//
	//	add: func(x: u32, y: u32) -> u32
	Add func(x uint32, y uint32) (result uint32)
}
