// Code generated by wit-bindgen-go. DO NOT EDIT.

package add

// This file contains wasmimport and wasmexport declarations for "dir:sdk@0.1.0".

//go:wasmexport dir:sdk/add@0.1.0#add
//export dir:sdk/add@0.1.0#add
func wasmexport_Add(x0 uint32, y0 uint32) (result0 uint32) {
	x := (uint32)((uint32)(x0))
	y := (uint32)((uint32)(y0))
	result := Exports.Add(x, y)
	result0 = (uint32)(result)
	return
}
