# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Release SDK

on:
  workflow_dispatch:
    inputs:
      javascript-release:
        required: false
        type: boolean
        description: "Make a javascript SDK release."
        default: false
      python-release:
        required: false
        type: boolean
        description: "Make a python SDK release."
        default: false
  workflow_call:
    inputs:
      javascript-release:
        required: false
        type: boolean
        description: "Make a javascript SDK release."
        default: false
      python-release:
        required: false
        type: boolean
        description: "Make a python SDK release."
        default: false

permissions:
  contents: read

jobs:
  python:
    name: Python
    if: ${{ inputs.python-release == true || inputs.python-release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Setup bin cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            bin/
          key: bin-cache-${{ runner.os }}-${{ hashFiles('bin/*') }}
          restore-keys: |
            bin-cache-${{ runner.os }}-

      - name: Install deps
        shell: bash
        run : |
          task deps

      - name: Build the Python package
        run: |
          task sdk:build:python

      - name: Publish the Python SDK
        run: |
          task sdk:release:python UV_PUBLISH_TOKEN=${{ secrets.PYPI_API_TOKEN }}

  javascript:
    name: JavaScript
    if: ${{ inputs.javascript-release == true || inputs.javascript-release == 'true' }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: https://registry.npmjs.org/
          scope: "@agntcy"

      - name: Setup bin cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            bin/
          key: bin-cache-${{ runner.os }}-${{ hashFiles('bin/*') }}
          restore-keys: |
            bin-cache-${{ runner.os }}-

      - name: Install deps
        shell: bash
        run : |
          task deps

      - name: Build the Javascript package
        run: |
          task sdk:deps:javascript
          task sdk:build:javascript

      - name: Publish the Javascript SDK
        run: |
          task sdk:release:javascript
